# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SMnZ1nYVZOw667UM0Ykds9hD1oJYnwD
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('students_dataset.csv')
print(df.head(10))

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

plt.plot(x, y1, label='Sine', color='blue')
plt.plot(x, y2, label='Cosine', color='orange')
plt.title("Sine and Cosine Waves")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()
plt.grid(True)
plt.show()

categories = ['A', 'B', 'C', 'D']
values = [10, 25, 15, 30]

plt.bar(categories, values, color='orange')
plt.title("Bar Chart Example")
plt.show()